### ISSUE TITLE
Call API from code not working

### ISSUE THREAD

**Issue by Ammar-Ishfaq** [EnsembleUI/ensemble#257] opened 2023-02-20 07:16 UTC
**Unable** to call **API via code** even the example get's **crashes** from the **"kitchen ensemble app"**

**Screenshot**:
![image](https://user-images.githubusercontent.com/54596139/220037375-5ffd3c6d-fdff-4dd6-b819-af89291fb692.png)

**More details**:
![image](https://user-images.githubusercontent.com/54596139/220037706-45510ce1-a87c-49a3-8ba2-67d6e4b17c52.png)

**Comment by amin-nas** [comment] 2023-02-20 16:12
@Ammar-Ishfaq thanks for reporting the issue. The issue was caused by calling an API that was not defined. The example is updated to call the correct API and it is working as expected. We will enhance the error messaging so it is clear what the issue is.

Do you have this issue in your own app? if so, please let us know.

**Comment by amin-nas** [comment] 2023-02-20 16:18
Issue created for enhancing the error message:
https://github.com/EnsembleUI/ensemble/issues/259

**Comment by kmahmood74** [comment] 2023-02-22 23:03
closing it as it is not an issue. We went through it in the meeting.

**Closed by kmahmood74** 2023-02-22 23:03 UTC
