### ISSUE TITLE
YouTube widget is showing up after navigation

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1530] opened 2024-08-05 14:52 UTC
https://studio.ensembleui.com/app/4DSXH4jwft26xOk3KabN/screen/9KJMKwBA6Yo0N6OHyyfi

Please check this example, This screen has a YouTube widget and when I click on the Navigate Button to navigate to next screen and click on the same place where YouTube Widget was placed before, video starts to play even though YouTube widget is not there in that widget. Seems like it overlays in second screen too.

**Comment by kmahmood74** [comment] 2024-08-05 14:56
this is a duplicate of #1522

**Closed by kmahmood74** 2024-08-05 14:56 UTC
