### ISSUE TITLE
Automatic handling of empty, error, and loading states

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#384] opened 2023-03-22 18:40 UTC
When I call APIs in Ensemble, I want Ensemble to handle loading, error, and empty state automatically so I dont have to define those myself.

**Comment by kmahmood74** [comment] 2023-07-27 17:25
@amin-nas please respond to Vinoth's question above

**Comment by vinothvino42** [comment] 2023-11-28 05:42
Duplicate of #833

**Closed by vinothvino42** 2023-11-28 05:42 UTC
Labels: enhancement
