### ISSUE TITLE
kitchen sink - clicking on Add Data in the ChartJs sample squishes the chart

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#271] opened 2023-02-22 00:57 UTC
it adds data but squishes the chart. Chart should keep its height and scale

**Comment by amin-nas** [comment] 2023-07-29 22:34
The issue is that the x axis labels rotate to accommodate for more labels.

![image](https://github.com/EnsembleUI/ensemble/assets/491202/7d415e66-49e2-49ce-94a2-9dd9ef39406f)


It can be resolved by disabling the rotation, and ChartJs automatically reduces number of labels.

![image](https://github.com/EnsembleUI/ensemble/assets/491202/814e7d3e-c5a6-4442-9094-0a588dd6e5d7)


Here's what needs to be added to ChartJS config to achieve that:

```javascript
    options: {
      scales: {
        x: {
          ticks: {
            maxRotation: 0,
            minRotation: 0
          }
        }
      }
   }
```

**Closed by amin-nas** 2023-07-29 22:34 UTC
Labels: bug
