### ISSUE TITLE
ensemble storage stored values not working for native apps 

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble#693] opened 2023-08-02 19:37 UTC
![image](https://github.com/EnsembleUI/ensemble/assets/62849614/f7ee5cb5-8500-4e37-829b-bed98c8d4e45)
![image](https://github.com/EnsembleUI/ensemble/assets/62849614/41565e5a-a46b-41c5-8ded-9eb662e31288)

- Above are all ss of the web preview for the Spark Savings App. 
- However, neither accounts nor the chart displays in the ensemble preview apps.

Note: For now i am unable to move to Home screen in android as i do, i ll share SS for that as well.

**Comment by kmahmood74** [comment] 2023-08-04 14:58
@sibteali786 please provide detailed replication steps. I have no idea what the issue is

**Comment by amin-nas** [comment] 2023-08-08 13:04
Fixed the definition and closing this as the issue is not related to storage. The JS code was throwing an error causing the storage not to be set.

@sibteali786 - keep in mind that on web you might have storage already set from another screen or previous screen loads. This causes the UI to work on web even if the new code setting the storage is throwing an error. Best to test after clearing the storage.

**Closed by amin-nas** 2023-08-08 13:04 UTC

**Comment by kmahmood74** [comment] 2023-08-08 13:17
Good catch @amin-nas

**Comment by sibteali786** [comment] 2023-08-08 15:25
@amin-nas Sure amin thanks for the info will take care of it in future, might be possible chart values not displaying for preview Apps have a similar issue may be.
